# Generated by Django 3.2.7 on 2021-11-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantar', '0006_alter_plantados_en_cuidado'),
        ('acceso', '0004_alter_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol_cuidador',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_elegido', models.DateTimeField(auto_now_add=True)),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plantar.plantados')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acceso.profile')),
            ],
        ),
    ]
