# Generated by Django 3.2.7 on 2021-11-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_access',
            old_name='user_id',
            new_name='user',
        ),
    ]
