# Generated by Django 3.2.7 on 2021-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_auto_20211117_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.CharField(default='login.jpg', max_length=100),
        ),
    ]
