# Generated by Django 3.2.5 on 2021-11-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arboles_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('regado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubi_coord', models.CharField(max_length=100)),
                ('ubi_text', models.CharField(max_length=100)),
                ('ult_regado', models.DateTimeField()),
                ('en_cuidado', models.BooleanField(default=True)),
                ('especificaciones', models.CharField(max_length=200)),
                ('dueño_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acceso.profile')),
                ('gen_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plantar.arboles_gen')),
            ],
        ),
    ]
