# Generated by Django 3.2.7 on 2021-11-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantados',
            old_name='dueño_id',
            new_name='dueño',
        ),
        migrations.RenameField(
            model_name='plantados',
            old_name='gen_id',
            new_name='gen',
        ),
    ]
