# Generated by Django 3.2.7 on 2021-11-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantar', '0002_auto_20211117_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantados',
            name='ult_regado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
