# Generated by Django 3.2.7 on 2021-11-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantar', '0003_alter_plantados_ult_regado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantados',
            old_name='gen',
            new_name='arbol_gen',
        ),
    ]
