# Generated by Django 3.2.7 on 2021-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantar', '0004_rename_gen_plantados_arbol_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantados',
            name='ubi_coord',
            field=models.CharField(default='', max_length=100),
        ),
    ]
